### ISSUE TITLE
자동완성 막기

### ISSUE THREAD

**Issue by skdonghyun** [skdonghyun/NextMes#75]
네, Tailwind CSS를 사용하고 계시다니 이해했습니다. Tailwind를 사용할 때도 autofill 문제를 해결할 수 있습니다. 다음과 같은 방법을 제안드립니다:

1. Tailwind의 `@apply` 디렉티브 사용:

`styles/globals.css` 또는 프로젝트의 메인 CSS 파일에 다음 코드를 추가하세요:

```css
@layer utilities {
  input:-webkit-autofill,
  input:-webkit-autofill:hover, 
  input:-webkit-autofill:focus {
    @apply bg-black text-white;
    -webkit-text-fill-color: white;
    -webkit-box-shadow: 0 0 0px 1000px #000 inset;
    transition: background-color 5000s ease-in-out 0s;
  }
}
```

이 방법은 Tailwind의 유틸리티 클래스를 사용하여 autofill 스타일을 오버라이드합니다.

2. 인라인 스타일 사용:

각 input 요소에 직접 스타일을 적용할 수 있습니다:

```jsx
<input
  className="bg-black text-white ..."
  style={{
    WebkitTextFillColor: 'white',
    WebkitBoxShadow: '0 0 0px 1000px #000 inset',
    transition: 'background-color 5000s ease-in-out 0s'
  }}
/>
```

3. Tailwind 설정 파일에 커스텀 스타일 추가:

`tailwind.config.js` 파일에 다음과 같이 커스텀 스타일을 추가할 수 있습니다:

```javascript
module.exports = {
  theme: {
    extend: {
      textFillColor: {
        'white': 'white',
      },
      boxShadow: {
        'input': '0 0 0px 1000px #000 inset',
      },
    },
  },
  plugins: [
    function({ addUtilities }) {
      const newUtilities = {
        '.autofill-black': {
          '&:-webkit-autofill': {
            '-webkit-text-fill-color': 'white',
            'box-shadow': '0 0 0px 1000px #000 inset',
            'transition': 'background-color 5000s ease-in-out 0s',
          },
        },
      }
      addUtilities(newUtilities, ['autofill', 'hover', 'focus'])
    }
  ],
}
```

그런 다음 input 요소에 이 클래스를 적용합니다:

```jsx
<input className="bg-black text-white autofill-black ..." />
```

이 방법들 중 프로젝트 구조와 선호도에 따라 가장 적합한 것을 선택하시면 됩니다. 첫 번째 방법이 가장 간단하고 전역적으로 적용할 수 있어 추천드립니다.

구현 과정에서 어려움이 있거나 추가 설명이 필요하시면 말씀해 주세요.

**Comment by skdonghyun** [comment]
알겠습니다. input 박스의 기본 색상을 유지하면서 autofill 스타일을 원래대로 돌리고 싶으시군요. Tailwind CSS를 사용하고 계시니, 다음과 같은 방법을 시도해 보실 수 있습니다:

1. Tailwind의 `@apply` 디렉티브 사용:

`styles/globals.css` 또는 프로젝트의 메인 CSS 파일에 다음 코드를 추가하세요:

```css
@layer utilities {
  input:-webkit-autofill,
  input:-webkit-autofill:hover, 
  input:-webkit-autofill:focus {
    @apply bg-white text-black;
    -webkit-text-fill-color: inherit;
    -webkit-box-shadow: 0 0 0px 1000px white inset;
    transition: background-color 5000s ease-in-out 0s;
  }
}
```

이 코드는 autofill된 input의 배경색을 흰색으로, 텍스트 색상을 검정색으로 설정합니다. 

2. Tailwind 설정 파일에 커스텀 스타일 추가:

`tailwind.config.js` 파일에 다음과 같이 커스텀 스타일을 추가할 수 있습니다:

```javascript
module.exports = {
  theme: {
    extend: {},
  },
  plugins: [
    function({ addUtilities }) {
      const newUtilities = {
        '.autofill-normal': {
          '&:-webkit-autofill': {
            '-webkit-text-fill-color': 'inherit',
            'box-shadow': '0 0 0px 1000px white inset',
            'transition': 'background-color 5000s ease-in-out 0s',
          },
        },
      }
      addUtilities(newUtilities, ['autofill', 'hover', 'focus'])
    }
  ],
}
```

그런 다음 input 요소에 이 클래스를 적용합니다:

```jsx
<input className="autofill-normal ..." />
```

3. 인라인 스타일 사용:

각 input 요소에 직접 스타일을 적용할 수 있습니다:

```jsx
<input
  className="..."
  style={{
    WebkitTextFillColor: 'inherit',
    WebkitBoxShadow: '0 0 0px 1000px white inset',
    transition: 'background-color 5000s ease-in-out 0s'
  }}
/>
```

이 방법들은 autofill 스타일을 기본 input 스타일과 유사하게 만듭니다. `white`와 `black` 대신 원하는 색상으로 변경할 수 있습니다.

가장 편리한 방법은 첫 번째 방법입니다. 이 방법을 사용하면 모든 input 요소에 전역적으로 적용되며, 개별 요소마다 클래스를 추가할 필요가 없습니다.

이 해결책들 중 하나를 시도해 보시고, 원하는 결과를 얻지 못하셨거나 추가 도움이 필요하시면 말씀해 주세요.​​​​​​​​​​​​​​​​

**Comment by skdonghyun** [comment]
죄송합니다. 제가 이해를 잘못했네요. input 박스의 색상을 전혀 변경하지 않고, Chrome의 autofill 기능이 적용되어도 원래의 스타일을 유지하고 싶으신 것이군요. 이 경우, 다음과 같은 방법을 사용할 수 있습니다:

1. Tailwind의 `@apply` 디렉티브 사용:

`styles/globals.css` 또는 프로젝트의 메인 CSS 파일에 다음 코드를 추가하세요:

```css
@layer utilities {
  input:-webkit-autofill,
  input:-webkit-autofill:hover, 
  input:-webkit-autofill:focus {
    -webkit-text-fill-color: inherit !important;
    -webkit-box-shadow: 0 0 0px 1000px transparent inset;
    transition: background-color 5000s ease-in-out 0s;
  }
}
```

2. Tailwind 설정 파일에 커스텀 스타일 추가:

`tailwind.config.js` 파일에 다음과 같이 커스텀 스타일을 추가할 수 있습니다:

```javascript
module.exports = {
  theme: {
    extend: {},
  },
  plugins: [
    function({ addUtilities }) {
      const newUtilities = {
        '.autofill-transparent': {
          '&:-webkit-autofill': {
            '-webkit-text-fill-color': 'inherit !important',
            'box-shadow': '0 0 0px 1000px transparent inset',
            'transition': 'background-color 5000s ease-in-out 0s',
          },
        },
      }
      addUtilities(newUtilities, ['autofill', 'hover', 'focus'])
    }
  ],
}
```

그런 다음 input 요소에 이 클래스를 적용합니다:

```jsx
<input className="autofill-transparent ..." />
```

3. 인라인 스타일 사용:

각 input 요소에 직접 스타일을 적용할 수 있습니다:

```jsx
<input
  className="..."
  style={{
    WebkitTextFillColor: 'inherit',
    WebkitBoxShadow: '0 0 0px 1000px transparent inset',
    transition: 'background-color 5000s ease-in-out 0s'
  }}
/>
```

이 방법들은 autofill이 적용되어도 input의 배경색을 변경하지 않습니다. 대신 투명한 배경을 사용하여 원래의 스타일을 그대로 유지합니다.

가장 간단한 방법은 첫 번째 방법입니다. 이 방법을 사용하면 모든 input 요소에 전역적으로 적용되며, 개별 요소마다 클래스를 추가할 필요가 없습니다.

이 해결책들 중 하나를 시도해 보시고, 원하는 결과를 얻지 못하셨거나 추가 도움이 필요하시면 말씀해 주세요.​​​​​​​​​​​​​​​​

**Comment by skdonghyun** [comment]
이해했습니다. 글자색까지 원래대로 유지하고 싶으시군요. 이 경우, autofill 시 글자색과 배경색 모두 변경되지 않도록 해야 합니다. 다음과 같은 방법을 시도해 보세요:

1. Tailwind의 `@apply` 디렉티브 사용:

`styles/globals.css` 또는 프로젝트의 메인 CSS 파일에 다음 코드를 추가하세요:

```css
@layer utilities {
  input:-webkit-autofill,
  input:-webkit-autofill:hover, 
  input:-webkit-autofill:focus,
  input:-webkit-autofill:active {
    -webkit-text-fill-color: inherit !important;
    -webkit-box-shadow: 0 0 0 30px transparent inset !important;
    transition: background-color 5000s ease-in-out 0s;
    background-clip: content-box !important;
  }
}
```

2. Tailwind 설정 파일에 커스텀 스타일 추가:

`tailwind.config.js` 파일에 다음과 같이 커스텀 스타일을 추가할 수 있습니다:

```javascript
module.exports = {
  theme: {
    extend: {},
  },
  plugins: [
    function({ addUtilities }) {
      const newUtilities = {
        '.autofill-inherit': {
          '&:-webkit-autofill, &:-webkit-autofill:hover, &:-webkit-autofill:focus, &:-webkit-autofill:active': {
            '-webkit-text-fill-color': 'inherit !important',
            'box-shadow': '0 0 0 30px transparent inset !important',
            'transition': 'background-color 5000s ease-in-out 0s',
            'background-clip': 'content-box !important',
          },
        },
      }
      addUtilities(newUtilities, ['autofill', 'hover', 'focus', 'active'])
    }
  ],
}
```

그런 다음 input 요소에 이 클래스를 적용합니다:

```jsx
<input className="autofill-inherit ..." />
```

3. 인라인 스타일 사용:

각 input 요소에 직접 스타일을 적용할 수 있습니다:

```jsx
<input
  className="..."
  style={{
    '&:-webkit-autofill, &:-webkit-autofill:hover, &:-webkit-autofill:focus, &:-webkit-autofill:active': {
      WebkitTextFillColor: 'inherit',
      WebkitBoxShadow: '0 0 0 30px transparent inset',
      transition: 'background-color 5000s ease-in-out 0s',
      backgroundClip: 'content-box'
    }
  }}
/>
```

이 방법들은 autofill이 적용되어도 input의 배경색과 글자색을 변경하지 않습니다. `inherit`를 사용하여 원래의 스타일을 그대로 유지합니다.

첫 번째 방법이 가장 간단하고 전역적으로 적용할 수 있어 추천드립니다. 

이 해결책들을 적용해보시고, 여전히 원하는 결과를 얻지 못하셨다면 말씀해 주세요. 추가적인 조정이 필요할 수 있습니다.​​​​​​​​​​​​​​​​
